GET http://localhost:5000


### Get all items
GET http://localhost:5000/api/v1/items


### Get single item
GET http://localhost:5000/api/v1/items/1


### Add item
POST http://localhost:5000/api/v1/items
Content-Type: application/json

{
    "name": "My Item"
}


### Update an item
PUT http://localhost:5000/api/v1/items/1
Content-Type: application/json

{
    "name": "My Item"
}


### Delete item
DELETE http://localhost:5000/api/v1/items/1
